name: Optional Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  pkcs11check:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "pkcs11check" || echo "::warning ::Job exited with status $?"
  debian_jdk11:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "debian_jdk11" || echo "::warning ::Job exited with status $?"
  ubuntu_jdk8:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "ubuntu_jdk8" || echo "::warning ::Job exited with status $?"
  fedora_latest_jdk11:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "fedora_latest_jdk11" || echo "::warning ::Job exited with status $?"
  fedora_rawhide:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "fedora_rawhide" || echo "::warning ::Job exited with status $?"
  fedora_sandbox:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "fedora_sandbox" || echo "::warning ::Job exited with status $?"
  centos7:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "centos_7" || echo "::warning ::Job exited with status $?"
  centos8:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "centos_8" || echo "::warning ::Job exited with status $?"
