name: Optional Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - 'pkcs11check'
          - 'debian_jdk11'
          - 'ubuntu_jdk8'
          - 'fedora_latest_jdk11'
          - 'fedora_rawhide'
          - 'fedora_sandbox'
          - 'centos_7'
          - 'centos_8'
          - 'pki_build'

    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
  
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "${{ matrix.image }}" || echo "::warning ::Job exited with status $?"
