name: Required Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['fedora_30', 'fedora_31', 'symbolcheck']
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "${{ matrix.image }}"
